name: nosmokingapp-dev

services:
  client:
    build:
      context: .
      dockerfile: development.Dockerfile
      target: dev-client
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    volumes:
      - ./:/src

  server:
    build:
      context: .
      dockerfile: development.Dockerfile
      target: dev-server
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    user: "${hOST_UID:-1000}:${HOST_GID:-1000}"
    ports:
      - "5218:5218"
    volumes:
      - ./:/src
      - persistent-data:/app/persistent_data
    develop:
      watch:
        - path: ./NoSmokingMap.csproj
          target: /src/NoSmokingMap.csproj
          action: rebuild
    post_start:
      - command: chown -R ${HOST_UID:-1000}:${HOST_GID:-1000} /app/persistent_data
        user: root

  https_proxy:
    image: caddy:latest
    ports:
      - "5219:5219"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
    depends_on:
      - server

volumes:
  persistent-data:
